# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
---
version: 2

before:
  hooks:
    - make package VERSION={{ .Version }}

builds:
  - id: binary
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: hello-world
    ldflags:
      - -s
      - -w

kos:
  - id: container-image
    build: binary
    repositories:
      - jooola/hello-world
    platforms:
      - linux/amd64
      - linux/arm64
    base_image: alpine
    bare: true
    user: 1000:1000
    labels:
      org.opencontainers.image.source: https://github.com/jooola/goreleaser-playground
    tags:
      - "{{.Tag}}"

archives:
  - id: archive
    ids:
      - binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

release:
  ids:
    - archive
  extra_files:
    - glob: ./package-*.tgz

publishers:
  - name: publish-helm-chart

    # Only execute once by filtering all ids, and only running for the checksum.
    ids: ["none"]

    cmd: ./publish-package.sh package-{{ .Version }}.tgz
    env:
      - CHART_REPO_REMOTE=https://github.com/jooola/goreleaser-playground
